## Data Splitter

In [4]:
import pandas as pd
df = pd.read_csv('contributors_df.csv')

In [7]:
# Mélanger la trame de données à l'aide de la fonction
df = df.sample(frac=1)
df

,Unnamed: 0,idcontributors,full_name,contributor_name,contributions,idrepositories
14249,14249,14249,hassio-addons/addon-uptime-kuma,frenck,29,502741572
32464,32464,32464,danstepanov/create-expo-stack,danstepanov,14,652905376
9422,9422,9422,lvonasek/QuestPiLauncher,kiksou,2,479834802
317,317,317,rukai/cargo-run-wasm,Liamolucko,1,443751660
12746,12746,12746,google-research/skai,rchen152,1,498922289
...,...,...,...,...,...,...
25309,25309,25309,haskell-game/tiny-games-hs,migmit,7,598562832
3417,3417,3417,MartinIngesen/TokenStomp,NotMedic,1,455372758
22133,22133,22133,moshi4/pyMSAviz,moshi4,31,565401161
30969,30969,30969,anupamkliv/FedERA,sshivaditya2019,5,640500079
28977,28977,28977,huzaifaarain/telescope-guzzle-watcher,jessarcher,3,626089857

In [8]:

# Select ratio
ratio_1 = 0.2
ratio_2 = 0.2
ratio_3 = 0.6

total_rows = df.shape[0]

# Calculer le nombre de rangées pour chaque partie
part1 = int(total_rows * ratio_1)
part2 = int(total_rows * (ratio_1 + ratio_2))
part3 = total_rows

# Diviser les données
part_JSON = df.iloc[:part1]
part_CSV = df.iloc[part1:part2] 
part_df = df.iloc[part2:]

In [9]:
part_JSON

,Unnamed: 0,idcontributors,full_name,contributor_name,contributions,idrepositories
14249,14249,14249,hassio-addons/addon-uptime-kuma,frenck,29,502741572
32464,32464,32464,danstepanov/create-expo-stack,danstepanov,14,652905376
9422,9422,9422,lvonasek/QuestPiLauncher,kiksou,2,479834802
317,317,317,rukai/cargo-run-wasm,Liamolucko,1,443751660
12746,12746,12746,google-research/skai,rchen152,1,498922289
...,...,...,...,...,...,...
4364,4364,4364,spiegelgraphics/speedskating,mtstahlspiegel,7,457798786
26132,26132,26132,swishjam/swishjam,alexdanilowicz,7,602223778
29735,29735,29735,martinseanhunt/slack-gpt,martinseanhunt,8,635061134
8315,8315,8315,songsong321/meet-uniapp,songsong321,11,476600128
29080,29080,29080,chenjiandongx/grogudb,chenjiandongx,8,626505846

In [18]:
part_JSON.to_json('part_JSON.json', orient='records', lines=True)

In [10]:
part_CSV

,Unnamed: 0,idcontributors,full_name,contributor_name,contributions,idrepositories
7265,7265,7265,RamiKrispin/atsaf,RamiKrispin,62,468994504
2666,2666,2666,ai03-2725/yet-another-keyboard-builder,dependabot[bot],1,448627208
774,774,774,tascj/kaggle-sartorius-cell-instance-segmentat...,tascj,2,444621683
27939,27939,27939,IIC2613-Inteligencia-Artificial-2023-1/Syllabus,vicentevegaulloa,1,614175187
13454,13454,13454,yuh-yang/MBHT-KDD22,yuh-yang,10,500349253
...,...,...,...,...,...,...
24673,24673,24673,ionic-team/capacitor-starters,Tommertom,1,590094382
10372,10372,10372,eth-clients/sepolia,Sepolia-Testnet,1,488159989
13336,13336,13336,fudan-zvg/Ego3RT,lzrobots,2,500423177
22690,22690,22690,PlummersSoftwareLLC/HelloAssembly,therontarigo,2,583842445
4303,4303,4303,sulab999/Taichi,sulab999,43,457840977

In [17]:
part_CSV.to_csv("part_CSV.csv")

In [11]:
part_df

,Unnamed: 0,idcontributors,full_name,contributor_name,contributions,idrepositories
16988,16988,16988,kubeedge/ianvs,luosiqi,3,512980605
20197,20197,20197,russellbanks/Komac,jackdevey,1,560207581
18402,18402,18402,pine64/OpenPineBuds,ThatcherC,26,541089040
25951,25951,25951,jamesopstad/typesafe-router,jamesopstad,106,601080579
1028,1028,1028,dlkj/usbd-human-interface-device,KoviRobi,1,445258253
...,...,...,...,...,...,...
25309,25309,25309,haskell-game/tiny-games-hs,migmit,7,598562832
3417,3417,3417,MartinIngesen/TokenStomp,NotMedic,1,455372758
22133,22133,22133,moshi4/pyMSAviz,moshi4,31,565401161
30969,30969,30969,anupamkliv/FedERA,sshivaditya2019,5,640500079
28977,28977,28977,huzaifaarain/telescope-guzzle-watcher,jessarcher,3,626089857

In [16]:
from sqlalchemy import create_engine
import pymysql

DB_HOST = 'localhost'
DB_USER = 'admin1'
DB_PASS = 'Youcode-1'
DB_NAME = 'data_splitter_df'

connection = pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASS, db=DB_NAME)

try:
    engine = create_engine(f'mysql+pymysql://{DB_USER}:{DB_PASS}@{DB_HOST}/{DB_NAME}')

    columns_contributors = [
        'idcontributors', 'full_name', 'contributor_name', 'contributions', 'idrepositories']

    df[columns_contributors].to_sql(name='Splitter_df', con=engine, if_exists='append', index=False)

    print("Data inserted successfully.")

except Exception as e:
    connection.rollback()
    print(f"Error: {str(e)}")

finally:
    connection.close()

Data inserted successfully.

C:\Users\Youcode\AppData\Local\Temp\ipykernel_63348\2070132402.py:17: UserWarning: The provided table name 'Splitter_df' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df[columns_contributors].to_sql(name='Splitter_df', con=engine, if_exists='append', index=False)